Access to the speech recognition service
xbmc/libandroidjni pull request #30
Opened 2022-04-28 16:26 UTC by joseluismarti

Add classes to access the speech recognition service: ```CJNISpeechRecognizer```, ```CJNIRecognitionListener``` and ```CJNIBundle```.

Add ```CJNIToast``` to show a brief notifications to the user.

In ```CJNIContext``` add calls to ```PopulateStaticFields()``` methods.

In ```CJNIPackageManager``` add ```PERMISSION_GRANTED``` and ```PERMISSION_DENIED``` fields.

New classes and changes work perfectly in runtime tests I am doing to incorporate this service in Kodi. 
Tested on Android 9 and 11.

2022-04-28 17:13 UTC, ksooo commented
> Add CJNIToast to show a brief notifications to the user.

 Does this mean a "native" dialog pops up on top of the skinned Kodi GUI? Why do we want that instead of a Kodi toast looking like the skinner wants it to look?

2022-04-28 18:19 UTC, joseluismarti commented
A Toast is a native view containing a quick little message for the user, appears as a floating view over the application. It will never receive focus and automatically disappear after a timeout.

I've tested it on Kodi and can be used without problem. My intention is use to alert the user that "it's listening..." or shows error in the speech process.

At the moment we can add this class to the library, maybe in Kodi we should use a GUI Toast as you suggest.

2022-04-28 19:34 UTC, ksooo commented
> A Toast is a native view containing a quick little message for the user ...

I know what a toast is and we already have this in Kodi. No need for a second, platform specific implemenatation, esp. as it can't be skinned. 

=> https://github.com/xbmc/xbmc/blob/master/xbmc/dialogs/GUIDialogKaiToast.h

2022-04-28 19:35 UTC, ksooo requested changes
-1 for the part of this PR that introduces another toast. Kodi already has that.

2022-04-28 21:17 UTC, ksooo commented
Please squash down to a single commit and this one is ready to go in, once the corresponding Kodi PR is reviewed and approved.

2022-04-29 00:34 UTC, garbear approved these changes
No problems here that I see.

2022-04-29 06:08 UTC, ksooo commented
@joseluismarti  cool, please open the corresponding PR for Kodi so we can see for what you actually need this changes. ;-)

2022-04-29 06:08 UTC, ksooo approved these changes

2022-05-03 09:28 UTC, merged